User.create(username:"bella", email:"bella@bella.com", password_digest: "bella")
User.create(username:"milo", email:"milo@milo.com", password_digest: "milo")
User.create(username:"dianne", email:"dianne@dianne.com", password_digest: "dianne")
User.create(username:"sarah", email:"sarah@milo.com", password_digest: "sarah")
User.create(username:"samba", email:"samba@bella.com", password_digest: "samba")
User.create(username:"smokey", email:"milo@milo.com", password_digest: "smokey")
User.create(username:"jenny", email:"dianne@dianne.com", password_digest: "jenny")
User.create(username:"snoopy", email:"sarah@milo.com", password_digest: "snoopy")
